#!/usr/bin/env bash
set -Eeuo pipefail
[[ $EUID -eq 0 ]] || { echo 'Run with sudo' >&2; exit 1; }
API=${SOLOMON_API:-http://127.0.0.1:8765};KEY=$(cat /etc/solomonprime/api.key);AUTH=(-H "Authorization: Bearer $KEY" -H 'Content-Type: application/json')
existing(){ curl -fsS -H "Authorization: Bearer $KEY" "$API/v1/goals?limit=500"|jq -r --arg n "$1" '.goals[]?|select(.name==$n)|.id'|head -1; }
create(){ local name="$1" outcome="$2" metrics="$3";local id;id=$(existing "$name");[[ -n "$id" ]]&&{ echo "$id";return; };jq -n --arg n "$name" --arg o "$outcome" --argjson m "$metrics" '{name:$n,outcome:$o,why:"Continuous improvement must be measured, reproducible, license-compliant, local-first, and human-governed.",owner:"research-simulation",status:"proposed",priority:"high",baseline:{measurement:"required"},target:{regression_free:true,benchmark_evidence:true},constraints:{free_use_licenses_only:true,local_first:true,no_unapproved_device_control:true,no_credential_capture:true},success_metrics:$m,stop_criteria:["accuracy regression","latency or energy regression without approved tradeoff","license uncertainty","unsafe capability expansion"],approval_requirements:["reproducible experiment","critic review","operator promotion approval","rollback artifact"]}'|curl -fsS "${AUTH[@]}" -d @- "$API/v1/goals"|jq -r .id; }
g1=$(create 'Memory and Retrieval Accuracy-Speed Optimization' 'Continuously benchmark lexical, hashed-vector, and approved semantic retrieval for accuracy, latency, memory use, and energy before promotion.' '["retrieval recall and precision","p50/p95 latency","peak RAM","energy per query","citation correctness"]')
g2=$(create 'Governed Reverse-Engineering Capability Expansion' 'Research and test open-source receive-first USB, serial, Bluetooth/BLE, Wi-Fi, SDR, and firmware-analysis tools on owned devices in an isolated lab.' '["hardware probe accuracy","protocol identification reproducibility","zero unapproved transmit/write operations","license manifest complete"]')
g3=$(create 'SolomonPrime Self-Performance Regression Lab' 'Measure answer accuracy, tool success, time-to-first-token, throughput, reliability, and cost/energy across local models and bounded free advisors.' '["task accuracy","tool-call completion","time to first token","tokens per second","job success","Wh per successful task"]')
jq -n --arg g1 "$g1" --arg g2 "$g2" --arg g3 "$g3" '{goals:[$g1,$g2,$g3],automatic_promotion:false}'
